Importing Libraries to assist in creation of dataFrame for data, creation of K-fold cross validation, standardization of values in dataframe, and logistic regression model.

In [25]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import numpy as np

Creating Dataframe as `dataFrame`

In [33]:
dataFrame = pd.read_csv('FRAFirm.csv')
dataFrame.head()

,FIRM,class,Start,End,Length,Night,Gap,WS,idx,Base,...,Trans,Press,p1s,p1l,p2s,p2l,MalAdj,NFZ,AFZ,MFZ
0,-10,0,290,610,320,0,999,0,6,5.0,...,-4.0,-4.67,0,0,0,0,0,0,0,0
1,-10,0,905,1265,360,0,295,0,6,5.0,...,-4.0,-4.67,-10,320,0,0,0,0,0,0
2,5,0,1040,1505,465,0,999,1,1,5.0,...,0.0,0.00,-10,360,-10,320,0,0,0,0
3,4,0,920,1295,375,0,855,0,2,5.0,...,0.0,-0.67,5,465,-10,360,0,0,0,0
4,1,0,1280,1775,495,1,999,1,1,2.0,...,-1.0,0.00,4,375,5,465,0,0,0,0

Creating a K Fold Cross Validation as `kfold`

In [16]:
kfold = KFold(n_splits = 10, shuffle = True, random_state=42)
model = LogisticRegression(max_iter=300)
accuracy_scores = []

Creating a standard scalar for the training data and test data. In this scalar we are creating a range from 0 to 1 to create minimal standard deviations of the features and preserve zero entries in sparse data. 

This will help with features such as NFZ, AFZ, and MFZ.

In [36]:
scaler = preprocessing.MinMaxScaler()

Seperating column `class` from the dataset to create the `y` series

In [39]:
y = dataFrame['class']
X = dataFrame[[col for col in dataFrame.columns if col != 'class']]
X.info()
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38759 entries, 0 to 38758
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FIRM      38759 non-null  int64
 1   Start     38759 non-null  int64
 2   End       38759 non-null  int64
 3   Length    38759 non-null  int64
 4   Night     38759 non-null  int64
 5   Gap       38759 non-null  int64
 6   WS        38759 non-null  int64
 7   idx       38759 non-null  int64
 8   Base      38759 non-null  float64
 9   StartAdj  38759 non-null  float64
 10  LenAdj    38759 non-null  float64
 11  Comp      38759 non-null  float64
 12  Trans     38759 non-null  float64
 13  Press     38759 non-null  float64
 14  p1s       38759 non-null  int64
 15  p1l       38759 non-null  int64
 16  p2s       38759 non-null  int64
 17  p2l       38759 non-null  int64
 18  MalAdj    38759 non-null  int64
 19  NFZ       38759 non-null  int64
 20  AFZ       38759 non-null  int64
 21  MFZ       38759 non-null  int64
dtypes: float64(6), int64(16)
memory usage: 6.5 MB
<class 'pandas.core.series.Series'>
RangeIndex: 38759 entries, 0 to 38758
Series name: class
Non-Null Count  Dtype
--------------  -----
38759 non-null  int64
dtypes: int64(1)
memory usage: 302.9 KB

In [48]:
X_test_minmax = scaler.fit_transform(X)
X_test_minmax_dataframe = pd.DataFrame(X_test_minmax)
X_test_minmax_dataframe.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.000000,0.201529,0.146,0.067579,0.0,1.000000,0.0,0.161290,1.0,0.458333,...,0.809524,0.894654,0.666667,0.000000,0.666667,0.000000,0.0,0.0,0.0,0.0
1,0.000000,0.628909,0.408,0.101796,0.0,0.295295,0.0,0.161290,1.0,0.458333,...,0.809524,0.894654,0.000000,0.226950,0.666667,0.000000,0.0,0.0,0.0,0.0
2,1.000000,0.722724,0.504,0.191617,0.0,1.000000,1.0,0.000000,1.0,1.000000,...,1.000000,1.000000,0.000000,0.255319,0.000000,0.226950,0.0,0.0,0.0,0.0
3,0.933333,0.639333,0.420,0.114628,0.0,0.855856,0.0,0.032258,1.0,1.000000,...,1.000000,0.984886,1.000000,0.329787,0.000000,0.255319,0.0,0.0,0.0,0.0
4,0.733333,0.889507,0.612,0.217280,1.0,1.000000,1.0,0.000000,0.0,1.000000,...,0.952381,1.000000,0.933333,0.265957,1.000000,0.329787,0.0,0.0,0.0,0.0

Create the K number of Folds and start cross validation to find coefficients for dataset. During this applying scaler fit_transform to set range from 0 to 1.

In [56]:
for train_index, test_index in kfold.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    X_train_minmax = pd.DataFrame(scaler.fit_transform(X_train)) 
    X_test_minmax = pd.DataFrame(scaler.fit_transform(X_test))
    
    model.fit(X_train_minmax, y_train)
    y_pred = model.predict(X_test_minmax)

    accuracy = accuracy_score(y_test, y_pred)
    accuracy_scores.append(accuracy)

print(accuracy_scores)

ValueError: Found input variables with inconsistent numbers of samples: [3876, 34883]

In [114]:
average_accuracy = np.mean(accuracy_scores)
print(f'Average Accuracy: {average_accuracy:.2f}')

Average Accuracy: 0.93